# Site settings
title: REWRITING LIFE
email: chewwl@gis.a-star.edu.sg
description: Gene, Genome, Genetics, Gene-targeting, Genome-editing, Genome-engineering, CRISPR-Cas9, Cas9, CRISPR, Cpf1, Cas12a, Cas13a, immune, immunogenicity, chew, wei, leong, Singapore, Institute, research, biology, DNA, RNA, technology, biotech, innovation, disease, protein engineering, therapeutics, therapy, medicine.
#baseurl: "" # the subpath of your site, e.g. /blog
url: https://chewlab.github.io
author: Wei Leong CHEW
street_address: 60 Biopolis Street
city: Singapore
zip_code: 138672
country: Singapore
phone: (65) 6808-8044

# icon: fa-circle # Font Awesome class for your site's icon

# Social settings
github_url: https://chewlab.github.io/
twitter_url: .

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
