# Site settings
title: Amy S. Tsai
email: astsai127@gmail.com
description: Researcher at Stanford University<br>MS4 at UC Davis School of Medicine
#baseurl: "" # the subpath of your site, e.g. /blog
url: https://astsai.github.io
author: Amy S. Tsai
street_address: 300 Pasteur Drive
city: Stanford
state: CA
zip_code: 94305
country: USA
phone: 

 icon: fa-flask # Font Awesome class for your site's icon

# Social settings
github_url: https://astsai.github.io/
twitter_url: . 

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
